(add-to-list 'display-buffer-alist '((category . dape-info-0)
                                     (display-buffer-in-side-window)
                                     (window-height . 0.8)
                                     (window-width . 0.3)))
(add-to-list 'display-buffer-alist '((category . dape-info-1)
                                     (display-buffer-in-side-window)
                                     (window-height . 0.2)
                                     (window-width . 0.3)))
(add-to-list 'display-buffer-alist '((category . dape-info-2)
                                     (display-buffer-in-side-window)
                                     (window-height . 0.1)
                                     (window-width . 0.3)))
